### ISSUE TITLE
URL in emails need to be updated to point to the new site

### ISSUE THREAD

**Issue by karentom** [springernature/snics-questionnaire#89]
In some emails where there is a link to the site, the URL needs to be updated to the new site.  

Below example is the questionnaire completed email. Please fix and check all other emails if the same issue exists.

![image](https://user-images.githubusercontent.com/17595871/54143774-e2f66c80-4400-11e9-8236-743ba3a73365.png)

**Comment by harshadporwal** [comment]
@karentom This is fixed and moved to LIVE.

**Comment by karentom** [comment]
@harshadporwal The questionnaire link in the Partner Questionnaire email is still pointing to the old site.

![image](https://user-images.githubusercontent.com/17595871/54574244-018ed180-49c6-11e9-916b-05a88d60c02b.png)

Clicking on 'Questionnaire link' took me to this URL: https://snics-questionnaire.springernature.com/en/?q=1044155291934952510131013#/

Please fix.

**Comment by harshadporwal** [comment]
@karentom This is not a issue. The URL which is available in mail is the external URL for questionnaire. We had a discussion some time back with Steph which URL should we put in the mail. So she suggested external link.

**Comment by karentom** [comment]
@harshadporwal Then why am I getting a message that the token is invalid? I created this in QA yesterday.

![image](https://user-images.githubusercontent.com/17595871/54616992-ec05c000-4a36-11e9-95a2-0d6102d7fb16.png)

**Comment by harshadporwal** [comment]
@karentom The above URL only works for LIVE system. Here you have created a token in QA and accessing through LIVE url that is why it is saying Questionnaire token invalid. If you want to test questionnaire app in QA, please go to partner details in employee portal and click Questionnaire button. It will redirect to questionnaire app.

![image](https://user-images.githubusercontent.com/43807299/54800499-45186280-4c88-11e9-85b7-653e07829ee8.png)
